<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="AwakeDrive provides live fleet safety monitoring for professional transport teams.">
    <title>AwakeDrive | Drive Awake, Arrive Better</title>
    <link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
    <link rel="apple-touch-icon" href="{{ asset('favicon.png') }}">
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=manrope:400,500,600,700,800" rel="stylesheet">
    <style>
        :root { --ink:#062f31; --deep:#04292b; --teal:#08716e; --mint:#dcefe8; --gold:#f4bf4f; --paper:#f6f7f1; --muted:#5d7473; }
        * { box-sizing:border-box; } html { scroll-behavior:smooth; } body { background:var(--paper); color:var(--ink); font-family:Manrope,sans-serif; margin:0; }
        .shell { margin:0 auto; max-width:76rem; padding:0 1.5rem; }.nav { align-items:center; display:flex; height:5.5rem; justify-content:space-between; position:relative; z-index:3; }
        .brand { align-items:center; color:#fff; display:inline-flex; font-size:1.08rem; font-weight:800; gap:.7rem; text-decoration:none; }.brand img { border-radius:.55rem; height:2.35rem; width:2.35rem; }.nav-actions,.hero-buttons,.hero-meta { display:flex; gap:.8rem; }.nav-actions { align-items:center; }.login-link { color:#c2e0d9; font-size:.84rem; font-weight:800; padding:.65rem; text-decoration:none; }
        .button { align-items:center; border:1px solid transparent; border-radius:.45rem; display:inline-flex; font-size:.86rem; font-weight:800; justify-content:center; padding:.83rem 1.15rem; text-decoration:none; transition:transform .2s ease,background .2s ease; }.button:hover { transform:translateY(-2px); }.button-gold { background:var(--gold); color:var(--ink); }.button-outline { border-color:rgb(236 253 245 / 45%); color:#f4fbf8; }
        .hero { background:var(--deep); color:#fff; min-height:41rem; overflow:hidden; position:relative; }.hero::before { background:linear-gradient(90deg,#04292b 9%,rgb(4 41 43 / 92%) 43%,rgb(4 41 43 / 35%) 100%); content:''; inset:0; position:absolute; z-index:1; }.hero::after { border:1px solid rgb(244 191 79 / 20%); content:''; height:22rem; position:absolute; right:-8rem; top:6rem; transform:rotate(45deg); width:22rem; z-index:1; }.hero-image { background:url('{{ asset('awakedrive_logo_first_concept.png') }}') 72% 48% / cover no-repeat; inset:0; opacity:.93; position:absolute; }.hero-content { max-width:43rem; padding:5.8rem 0 3rem; position:relative; z-index:2; }
        .eyebrow,.section-label,.board-kicker { color:#a8d7cc; font-size:.72rem; font-weight:800; letter-spacing:.14em; text-transform:uppercase; }.eyebrow { align-items:center; display:flex; gap:.65rem; }.eyebrow::before { background:var(--gold); content:''; height:.55rem; width:.55rem; } h1 { font-size:clamp(3rem,6vw,5.6rem); letter-spacing:0; line-height:.98; margin:1.25rem 0 1.45rem; } h2 { font-size:clamp(2rem,4.2vw,3.5rem); letter-spacing:0; line-height:1.08; margin:.75rem 0 0; }.hero-copy { color:#d4e8e2; font-size:1.06rem; line-height:1.8; max-width:34rem; }.hero-buttons { flex-wrap:wrap; margin-top:2rem; }.hero-meta { gap:2rem; margin-top:3.2rem; }.hero-meta div { border-left:2px solid var(--gold); padding-left:.7rem; }.hero-meta strong { display:block; font-size:.86rem; }.hero-meta span { color:#a4c8bf; font-size:.72rem; }
        .signal-band { background:var(--gold); color:var(--ink); }.signals { display:grid; grid-template-columns:repeat(3,1fr); }.signal { align-items:center; border-right:1px solid rgb(6 47 49 / 20%); display:flex; gap:.9rem; min-height:5.7rem; padding:1rem 1.1rem; }.signal:last-child { border:0; }.signal-index { border:1px solid rgb(6 47 49 / 38%); border-radius:50%; display:grid; font-size:.7rem; font-weight:800; height:1.8rem; place-items:center; width:1.8rem; }.signal strong { display:block; font-size:.9rem; }.signal span { display:block; font-size:.72rem; font-weight:700; margin-top:.12rem; }
        .overview { padding:6.5rem 0; }.section-label { color:var(--teal); }.overview-top { align-items:end; display:grid; gap:3rem; grid-template-columns:1.1fr .9fr; }.overview-copy { color:var(--muted); font-size:.98rem; line-height:1.8; margin:0; }.operations-board { background:var(--ink); color:white; display:grid; grid-template-columns:1.25fr .75fr; margin-top:4rem; min-height:22rem; overflow:hidden; }.board-main { padding:2.3rem; position:relative; }.board-main::after { background-image:linear-gradient(rgb(169 218 203 / 13%) 1px,transparent 1px),linear-gradient(90deg,rgb(169 218 203 / 13%) 1px,transparent 1px); background-size:2.5rem 2.5rem; content:''; inset:0; position:absolute; }.board-content { position:relative; z-index:1; }.board-main h3 { font-size:1.8rem; line-height:1.2; margin:.75rem 0 1.5rem; max-width:25rem; }.route { align-items:center; display:flex; gap:.7rem; max-width:25rem; }.route-point { background:#f4bf4f; border-radius:50%; height:.7rem; width:.7rem; }.route-point.finish { background:#78dbb7; }.route-line { border-top:2px dashed #87b7aa; flex:1; }.route-labels { color:#cde6df; display:flex; font-size:.75rem; justify-content:space-between; margin-top:.5rem; max-width:25rem; }.board-side { background:#0b4647; display:flex; flex-direction:column; justify-content:space-between; padding:2.3rem; }.live-status { align-items:center; color:#a7dbc7; display:flex; font-size:.75rem; font-weight:800; gap:.5rem; text-transform:uppercase; }.live-status i { background:#7be1b8; border-radius:50%; height:.55rem; width:.55rem; }.alert-count { color:var(--gold); font-size:3.5rem; font-weight:800; line-height:1; }.board-side p { color:#bbd8d1; font-size:.84rem; line-height:1.6; margin:.5rem 0 0; }
        .capabilities { border-top:1px solid #c9d9d3; display:grid; grid-template-columns:repeat(3,1fr); margin-top:4rem; }.capability { border-right:1px solid #c9d9d3; padding:1.8rem 1.5rem 1.2rem 0; }.capability + .capability { padding-left:1.5rem; }.capability:last-child { border:0; }.capability-number { color:var(--teal); font-size:.75rem; font-weight:800; }.capability h3 { font-size:1.08rem; margin:.85rem 0 .5rem; }.capability p { color:var(--muted); font-size:.88rem; line-height:1.7; margin:0; }.cta { background:var(--mint); padding:5.5rem 0; }.cta-inner { align-items:center; display:flex; gap:3rem; justify-content:space-between; }.cta .button { background:var(--teal); color:white; flex:0 0 auto; }footer { background:var(--deep); color:#a9ccc4; font-size:.78rem; padding:1.4rem 0; }.footer-row { align-items:center; display:flex; justify-content:space-between; }
        @media (max-width:700px) { .shell { padding:0 1.1rem; }.login-link { display:none; }.hero { min-height:42rem; }.hero::before { background:rgb(4 41 43 / 85%); }.hero-image { background-position:64% center; }.hero-content { padding:4.7rem 0 3rem; }.hero-meta { gap:1.1rem; margin-top:2.5rem; }.signals,.overview-top,.operations-board,.capabilities { grid-template-columns:1fr; }.signal,.capability { border-bottom:1px solid rgb(6 47 49 / 20%); border-right:0; }.capability,.capability + .capability { padding:1.4rem 0; }.overview { padding:4.5rem 0; }.operations-board { margin-top:3rem; }.board-main,.board-side { padding:1.7rem; }.board-side { min-height:12rem; }.cta-inner { align-items:flex-start; flex-direction:column; gap:1.5rem; }.footer-row { align-items:flex-start; flex-direction:column; gap:.6rem; } }
    </style>
</head>
<body>
    <main>
        <section class="hero"><div class="hero-image" aria-hidden="true"></div><div class="shell nav"><a class="brand" href="{{ route('landing') }}"><img src="{{ asset('favicon.png') }}" alt="AwakeDrive"> AwakeDrive</a><div class="nav-actions"><a class="login-link" href="{{ url('/admin/login') }}">Sign in</a><a class="button button-gold" href="{{ url('/admin') }}">Open control center</a></div></div><div class="shell hero-content"><div class="eyebrow">Driver safety intelligence</div><h1>Drive awake.<br>Arrive better.</h1><p class="hero-copy">A live command center for transport teams who need to understand every active trip, driver attention signal, and fleet exception before it becomes a risk.</p><div class="hero-buttons"><a class="button button-gold" href="{{ url('/admin') }}">Open control center</a><a class="button button-outline" href="#operations">Explore operations</a></div><div class="hero-meta"><div><strong>Live fleet view</strong><span>Active trips, mapped</span></div><div><strong>Safety signals</strong><span>Drowsy and microsleep alerts</span></div><div><strong>Built for teams</strong><span>Company-level controls</span></div></div></div></section>
        <section class="signal-band"><div class="shell signals"><div class="signal"><div class="signal-index">01</div><div><strong>Monitor</strong><span>See every active trip at a glance</span></div></div><div class="signal"><div class="signal-index">02</div><div><strong>Recognize</strong><span>Spot driver attention warnings early</span></div></div><div class="signal"><div class="signal-index">03</div><div><strong>Respond</strong><span>Keep your operation in control</span></div></div></div></section>
        <section class="overview" id="operations"><div class="shell"><div class="overview-top"><div><div class="section-label">Operational clarity</div><h2>Safety signals in the flow of every trip.</h2></div><p class="overview-copy">AwakeDrive connects the vehicle, driver, route, and destination in a single operational record. Your teams get a useful picture of safety status and fleet movement without hunting through separate systems.</p></div><div class="operations-board"><div class="board-main"><div class="board-content"><div class="board-kicker">Trip intelligence</div><h3>Track the route. Understand the driver. Know what needs attention.</h3><div class="route"><span class="route-point"></span><span class="route-line"></span><span class="route-point finish"></span></div><div class="route-labels"><span>Trip start</span><span>Planned destination</span></div></div></div><div class="board-side"><div class="live-status"><i></i> Live monitoring</div><div><div class="alert-count">24/7</div><p>Operational visibility for every trip your team is responsible for.</p></div></div></div><div class="capabilities"><article class="capability"><div class="capability-number">01</div><h3>Live trip monitoring</h3><p>Track active routes with current vehicle telemetry and location signals on a shared fleet map.</p></article><article class="capability"><div class="capability-number">02</div><h3>Driver attention alerts</h3><p>Bring drowsiness and microsleep events to the surface while the trip is still active.</p></article><article class="capability"><div class="capability-number">03</div><h3>Controlled access</h3><p>Give each company the right view of its people, devices, trips, and safety alerts.</p></article></div></div></section>
        <section class="cta"><div class="shell cta-inner"><div><div class="section-label">AwakeDrive control center</div><h2>Safety operations, ready when your team is.</h2></div><a class="button" href="{{ url('/admin/login') }}">Sign in to AwakeDrive</a></div></section>
    </main>
    <footer><div class="shell footer-row"><span>AwakeDrive</span><span>Drive awake, arrive better.</span></div></footer>
</body>
</html>
